camunda:
  bpm:
    admin-user:
      id: hubi
      password: 3Pass
      first-name: Hubert
    filter:
      create: All tasks
    database:
      jdbc-batch-processing: false

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/BPMN
    username: bpmn_user
    password: 2Pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8081

restapiuri: http://localhost:8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
