camunda:
  bpm:
    client:
      base-url: http://localhost:8081/engine-rest  # uri uderzające na Camundę
      lock-duration: 5000 # czas w [ms], przez który External Tasks są zablokowane zanim będą mogły być sfetchowane ponownie
      subscriptions:
        userCheckNewCopy: # nazwa topicu
          process-definition-key-in: First_process,Second_process # nazwy procesów, które startujemy w Camundzie
        userCheckOneMoreNewCopy: # nazwa topicu
          variable-names: firstName, lastName, userEmail, age # fetchujemy tylko te variablasy, domyślnie wszystkie są fetchowane, jeśli nie chcemy żadnej to wpisujemy []
          process-definition-key: First_process # nazwa procesu, który startujemy w Camundzie

logging:
  level:
    org:
      camunda:
        bpm:
          client: DEBUG # zwiększenie ilości logów

server:
  port: 8083
