spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/events
    username: events_user
    password: Pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
